import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="h-screen bg-[#121212] flex items-center justify-center">
      <Head>
        <title>Coin base clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-center text-4xl text-white">Coin base Clone 🚀</h1>
    </div>
  );
}
